const DELIVERY_TYPE = {
  NOVAPOST: 'NOVAPOST',
  UKRPOST: 'UKRPOST',
  SELFPICKUP: 'SELFPICKUP',
  NOVAPOSTCOURIER: 'NOVAPOSTCOURIER',
  UKRPOSTCOURIER: 'UKRPOSTCOURIER',
  WORLDWIDE: 'WORLDWIDE',
};

module.exports = {
  DELIVERY_TYPE,
};
