const DELIVERY_TYPE = {
  NOVAPOST: 'NOVAPOST',
  UKRPOST: 'UKRPOST',
  SELFPICKUP: 'SELFPICKUP',
  NOVAPOSTCOURIER: 'NOVAPOSTCOURIER',
  UKRPOSTCOURIER: 'UKRPOSTCOURIER',
  WORLDWIDE: 'WORLDWIDE',
};

const COUNTRY_OPTIONS = {
  WITHIN_UKRAINE: 'WITHIN_UKRAINE',
  WORLDWIDE: 'WORLDWIDE',
};

module.exports = {
  DELIVERY_TYPE,
  COUNTRY_OPTIONS,
};
