const EmailActions = {
  RECOVER_PASSWORD: 'RECOVER_PASSWORD',
  CONFIRM_EMAIL: 'CONFIRM_EMAIL',
  SUCCESSFUL_CONFIRM: 'SUCCESSFUL_CONFIRM',
  BLOCK_USER: 'BLOCK_USER',
  UNLOCK_USER: 'UNLOCK_USER',
  SUCCESSFUL_ORDER: 'SUCCESSFUL_ORDER',
  CONFIRM_ADMIN_EMAIL: 'CONFIRM_ADMIN_EMAIL',
  PAYMENT_ORDER: 'PAYMENT_ORDER',
  CONFIRM_CREATION_SUPERADMIN_EMAIL: 'CONFIRM_CREATION_SUPERADMIN_EMAIL',
  SEND_EMAIL_ANSWER: 'SEND_EMAIL_ANSWER',
  CERTIFICATE_REMINDER: 'CERTIFICATE_REMINDER',
  CERTIFICATE_EMAIL: 'CERTIFICATE_EMAIL',
};

module.exports = { EmailActions };
