const HISTORY_ACTIONS = {
  ADD_CATEGORY: 'ADD_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  ADD_CLOSURE: 'ADD_CLOSURE',
  EDIT_CLOSURE: 'EDIT_CLOSURE',
  DELETE_CLOSURE: 'DELETE_CLOSURE',
};

module.exports = {
  HISTORY_ACTIONS,
};
