const HISTORY_ACTIONS = {
  ADD_EVENT: 'ADD_EVENT',
  EDIT_EVENT: 'EDIT_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  BLOCK_EVENT: 'BLOCK_EVENT',
  UNLOCK_EVENT: 'UNLOCK_EVENT',
  REGISTER_EVENT: 'REGISTER_EVENT',
};

const HISTORY_NAMES = {
  CATEGORY_EVENT: 'CATEGORY_EVENT',
  CLOSURE_EVENT: 'CLOSURE_EVENT',
  COLOR_EVENT: 'COLOR_EVENT',
  MATERIAL_EVENT: 'MATERIAL_EVENT',
  MATERIAL_ABOUT_EVENT: 'MATERIAL_ABOUT_EVENT',
  MODEL_EVENT: 'MODEL_EVENT',
  NEWS_EVENT: 'NEWS_EVENT',
  PATTERN_EVENT: 'PATTERN_EVENT',
  PRODUCT_EVENT: 'PRODUCT_EVENT',
  USER_EVENT: 'USER_EVENT',
  ADMIN_EVENT: 'ADMIN_EVENT',
  POCKET_EVENT: 'POCKET_EVENT',
  BACK_EVENT: 'BACK_EVENT',
  BOTTOM_EVENT: 'BOTTOM_EVENT',
  POSITION_EVENT: 'POSITION_EVENT',
  STRAP_EVENT: 'STRAP_EVENT',
  BASIC_EVENT: 'BASIC_EVENT',
  CONSTRUCTOR_ELEMENT_EVENT: 'CONSTRUCTOR_ELEMENT_EVENT',
  CONSTRUCTOR_EVENT: 'CONSTRUCTOR_EVENT',
  RESTRICTION_EVENT: 'RESTRICTION_EVENT',
};

module.exports = {
  HISTORY_ACTIONS,
  HISTORY_NAMES,
};
