const INPUT_FIELDS = {
  USER: 'user',
  LOGIN_INPUT: 'loginInput',
  EMAIL: 'email',
  PASSWORD: 'password',
  CATEGORY: 'category',
  QUANTITY: 'quantity',
  ORDER: 'order',
  LIMIT: 'limit',
  SKIP: 'skip',
  DATE: 'date',
  POCKET: 'pocket',
  RESTRICTION: 'restriction',
  BACK: 'back',
  CLOSURE: 'closure',
  CONSTRUCTOR_ELEMENT: 'constructorElement',
  CONSTRUCTOR_BASIC: 'constructorBasic',
  CONSTRUCTOR_BOTTOM: 'constructorBottom',
  CONSTRUCTOR_FRONT_POCKET: 'constructorFrontPocket',
  STRAP: 'strap',
  PATTERN: 'pattern',
  SIZE: 'size',
  MODEL: 'model',
  CONTACT: 'contact',
  REPLY_COMMENT_DATA: 'replyCommentData',
};

module.exports = {
  INPUT_FIELDS,
};
