const ORDER_STATUSES = {
  ORDER_CREATED: 'CREATED',
  CONFIRMED: 'CONFIRMED',
  PRODUCED: 'PRODUCED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
};

const PAYMENT_METHODS = {
  CARD: 'CARD',
  CASH: 'CASH',
};

const PAYMENT_STATUSES = {
  CREATED: 'CREATED',
  EXPIRED: 'EXPIRED',
  APPROVED: 'APPROVED',
  DECLINED: 'DECLINED',
  REVERSED: 'REVERSED',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
};

const SENT_BY = 'sentBy';

const EMPTY_STRING = '';

module.exports = {
  ORDER_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  SENT_BY,
  EMPTY_STRING,
};
