const PAYMENT_METHOD = {
  CASH: 'CASH',
};
const PAYMENT_ACTIONS = {
  GO_TO_CHECKOUT: 'GO_TO_CHECKOUT',
  CHECK_PAYMENT_STATUS: 'CHECK_PAYMENT_STATUS',
};

const PAYMENT_DESCRIPTION = 'Оплата замовлення';

module.exports = {
  PAYMENT_METHOD,
  PAYMENT_DESCRIPTION,
  PAYMENT_ACTIONS,
};
